star/star/Source/Core/Theme/Fonts.swift
star/star/Source/DefaultViewController.swift

- 의견에 의해 Fonts -> Font로 바꿨던 게 문제가 발생 (이미 Font로 선언된 게 있음)
- 다시 Fonts로 Rename하는 리팩토링
어떤 변경 사항이 있나요?
- 다음에는 리소스가 소모되지 않도록 충분히 검토하는 게 좋겠습니다 ^^7
- develop을 중간에 pull해서 `Font` 기준으로 작업하신 분들은 `Fonts`로 다 바꿔주시는 게 필요할 것 같습니다.

[Refactor] Rename: Font -> Fonts

---

star/star/Source/Glass/GlassPlaceholder.swift
star/star/Source/Glass/StarModalView.swift
star/star/Source/Glass/StarModalViewController.swift

#10
- GlassPlaceholder 파일 삭제
- StarModalView 파일 추가 및 구현
- StarModalViewController 파일 추가 및 구현
어떤 변경 사항이 있나요?
- 시작시간, 종료시간을 버튼으로 구현해서 버튼 클릭시 DataPicker를 모달에 띄워 선택하는 방식으로 구현할 예정입니다. 혹시 더 좋은 의견 있으시면 말씀해주세요

[Feat] 스타 모달 UI 구현

---

star/star/Source/Core/UIComponent/GradientApplicable.swift
star/star/Source/Core/UIComponent/GradientView.swift
star/star/Source/DefaultViewController.swift

closes #38 
- GradientApplicable 프로토콜 구현
- GradientView, GradientButton은 해당 프로토콜을 채택함
- 해당 프로토콜을 채택하면 applyGradient 메서드가 자동으로 구현됨
- GradientDirection은 이제 뷰 속성값이 아닌 메서드 매개변수로 받음
- 아래 공유사항에서 자세하게 다룸
어떤 변경 사항이 있나요?
- @name-mun 스타 태그는 UIView() 가 아닌 GradientView()로 구현하면 applyGradient 메서드를 사용할 수 있습니다.
- @name-mun @AhnJunGyung applyGradient 메서드 적용 방법은 아래와 같이 바뀌었으니 참조 부탁드립니다!
```swift
private let addStarButton = GradientButton(type: .system).then {
$0.setTitle("스타 추가하기", for: .normal)
$0.setTitleColor(.starPrimaryText, for: .normal)
$0.titleLabel?.font = Fonts.buttonTitle
$0.backgroundColor = .starDisabledTagBG // 그라디언트가 정상적으로 적용될 시 배경색은 보이지 않음
$0.layer.cornerRadius = 28
$0.clipsToBounds = true
// $0.gradientDirection = .horizontal // 이제는 속성값으로 받지 않고 매개변수로 받음 (아래 참조)
}
// ... …
```

스타 태그 그라디언트 적용 구현 #38

---

star/star/Source/Core/UIComponent/GradientApplicable.swift

closes #42 
- 이제 3개 이상의 색깔을 추가해도 자동으로 적용됨
어떤 변경 사항이 있나요?
예시)
```swift
addStarButton.applyGradient(colors: [.starButtonPurple, .starButtonNavy, .systemRed], direction: .horizontal)
```
- 승인 과정 없이 바로 merge하겠습니다.
- 예상되는 conflicts가 없습니다.

applyGradient 메서드 개선 #42

---

star/star/App/SceneDelegate.swift

closes #44
- DefaultViewController() 인스턴스가 생성되고 사용되지 않고 있음
- 필요없는 코드를 삭제하고 window.rootViewController = StarListViewController() 인스턴스로 연결하는 코드 정리
어떤 변경 사항이 있나요?
- 예상되는 conflicts가 없어 바로 merge 하겠습니다.

SceneDelegate 코드 정리 #44

---

star/star/Source/Glass/StarModalView.swift
star/star/Source/Glass/StarModalViewController.swift

#19
- StarModalViewController에 텍스트 필드 선택했을때 올라오는 내장 키보드를 내리는 로직 구현

어떤 변경 사항이 있나요?

스타 생성/수정 모달 텍스트필드 입력처리 #19

---

star/star/App/star.xcdatamodeld/star.xcdatamodel/contents
star/star/Source/Eden/CoreDataManager.swift

#51
CoreData 의 Star -> StarEntity 타입명 수정
어떤 변경 사항이 있나요?

[Fix] CoreData 타입명 중복 수정

---

star/star.xcodeproj/project.pbxproj
star/star/App/App.entitlements
star/star/App/Info.plist
star/star/App/starRelease.entitlements
star/star/Source/Eden/CoreDataManager.swift

#8 
- .entitlements 파일 생성 후 설정
- Info.plist에서 권한 설정
어떤 변경 사항이 있나요?
SceneDelegate 설정은 온보딩뷰 구현 후 적용하겠습니다.

entitlements 파일 생성 후 Family Controls 접근 권한 생성

---

star/star/Resource/Colors.xcassets/starAlertBG.colorset/Contents.json
star/star/Resource/Colors.xcassets/starDeleteColor.colorset/Contents.json
star/star/Source/Core/Theme/Fonts.swift

closes #57 
- 커스텀 알럿 뷰 추가를 위한 색상 및 Fonts 추가
- starAlertBG, starDeleteColor,
- buttonDescription
어떤 변경 사항이 있나요?
- 승인 없이 바로 merge 하겠습니다.

커스텀 알럿 뷰 추가를 위한 색상 및 Fonts 추가 #57

---

star/star.xcodeproj/project.pbxproj
star/star.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

#61 
RxSwift 라이브러리를 추가했습니다.
어떤 변경 사항이 있나요?

RxSwift 라이브러리 추가 #61

---

star/star/Source/Glass/StarModalView.swift

#50 
- 도일님이 제안해주신 텍스트필드 삭제 버튼 구현했습니다.
- 추가 작업 : 레이아웃 세부 조정, 수정하기/생성하기 버튼 구현 및 그라디언트 적용
어떤 변경 사항이 있나요?
화이팅

텍스트필드 삭제 버튼 구현 #50

---

star/star/Source/Jerry/Star/MockData.swift
star/star/Source/Jerry/Star/Schedule/Schedule.swift
star/star/Source/Jerry/Star/Schedule/StarTime/StarTime.swift
star/star/Source/Jerry/Star/Schedule/StarTime/StarTimeFormatter.swift
star/star/Source/Jerry/Star/Schedule/StarTime/StarTimeTranslator.swift
star/star/Source/Jerry/Star/Schedule/WeekDay/WeekDay.swift
star/star/Source/Jerry/Star/Schedule/WeekDay/WeekDayFormatter.swift
star/star/Source/Jerry/Star/Schedule/WeekDay/WeekDayTranslator.swift
star/star/Source/Jerry/Star/Star.swift
star/star/Source/Jerry/Star/TestDescriptionConvertible.swift
star/star/Source/Jerry/StarState/StarState.Style.swift
star/star/Source/Jerry/StarState/StarState.swift

#66 
StarTime 생성자 오류 수정
Star 데이터 모델 MockData 추가 
어떤 변경 사항이 있나요?
TestDescriptionConvertible 프로토콜을 통해 데이터를 확인할 수 있게 만들었습니다.

StarTime 생성자 재귀 오류 수정 #66

---

star/star/Source/Jerry/Star/MockData.swift
star/star/Source/Jerry/Star/Schedule/StarTime/StarTimeFormatter.swift
star/star/Source/Jerry/Star/Schedule/WeekDay/WeekDay.swift
star/star/Source/Jerry/Star/Star.swift
star/star/Source/Jerry/StarState/ScheduleCalculator.swift
star/star/Source/Jerry/StarState/StarState.Style.swift
star/star/Source/Jerry/StarState/StarState.swift
star/star/Source/Jerry/StarState/StarStateFormatter.swift

#24 
SchduleCalculator 를 통해 Star 의 진행상황 연산을 구현했습니다.
어떤 변경 사항이 있나요?
@name-mun 
`Star` 의 `state()` 인스턴스 메서드를 통해 `StarState` 를 반환해줍니다.
`StarStateFormatter` 를 StarState의 남은 시간에 대한 문자열 형식 지원하고 있습니다.

ScheduleCalculator 구현 # 24

---

star/star/Source/Jerry/Star/MockData.swift
star/star/Source/Jerry/Star/Schedule/Schedule.swift
star/star/Source/Jerry/Star/Star.swift
star/star/Source/Jerry/StarState/ScheduleCalculator.swift
star/star/Source/Jerry/StarState/StarState.swift

#74 
StarState 남은시간 연산 및 정렬 연산 오류를 수정했습니다.
테스트용 MockData 를 추가했습니다.
어떤 변경 사항이 있나요?
@name-mun - MockData.stars 를 통해 테스트용 데이터를 사용하실 수 있습니다.
시간에 따라 진행상황이 잘 반영되는지 확인 부탁드립니다.
추가로 확인해보면 좋을 사항에 대해서 알려주시면 감사합니다.
현재 수정한 내용
- 진행중 < 대기중, 이후 남은 시간을 통한 정렬
- 진행중과 대기중인 경우의 남은 시간 연산

StarState 버그 수정 #74

---

star/star/Source/Glass/StarModalView.swift
star/star/Source/Glass/StarModalViewController.swift
star/star/Source/Glass/StarModalViewModel.swift

#70 
- MVVM으로 파일 구조 변경
- 요일 버튼 클릭시 gradient 적용
- 기존 UI 이벤트 RxCocoa로 수정
어떤 변경 사항이 있나요?

스타 생성하기/수정하기 모달 MVVM 리팩토링 #70

---

star/star/Source/Mun/StarList/StarListViewModel/StarListCollectionViewCellViewModel.swift

#81 
타이머가 처음 1초만 실행되고 멈추는 오류를 해결했습니다.
어떤 변경 사항이 있나요?
- 타이머 `observable`에 `period`를 추가하여 버그를 해결했습니다.

타이머 작동 오류 문제 해결

---

star/star/Source/Glass/StarModalView.swift
star/star/Source/Glass/StarModalViewController.swift
star/star/Source/Glass/StarModalViewModel.swift

#23
- 테스트 할 수 있도록 목데이터를 생성할 수 있게 구현했습니다.
- 내장 키보드 제어하는 로직을 RxCocoa로 수정한 내용이 반영됐습니다.
어떤 변경 사항이 있나요?
- 추후 실 데이터 저장하도록 구현하겠습니다.

[Feat] 스타 생성하기 (목 데이터) 구현

---

star/star/Source/Jerry/Onboarding/OnboardingView.swift
star/star/Source/Jerry/Onboarding/OnboardingViewController.swift
star/star/Source/Mun/StarList/StarListView/StarListViewController.swift

#27 
온보딩 페이지를 구현했습니다.
어떤 변경 사항이 있나요?
@name-mun 
`StarListViewController` 의 `viewWillAppear`를 통해 온보딩 페이지를 보여주는 형태로 연결시켰습니다.
`StarDeleteAlertViewController` 모달 애니메이션을`false`로 설정하는게 자연스러울 것 같습니다. 

온보딩 페이지 구현 #27

---

star/star/App/SceneDelegate.swift

#89 
앱 실행 시 권한 승인 상태여도 PermissionViewController가 먼저 표시되는 오류 수정
어떤 변경 사항이 있나요?
버그 수정했습니다.

앱 실행 시 권한 승인 상태여도 PermissionViewController가 먼저 표시되는 오류 수정

---

star/star/Source/Jerry/Onboarding/OnboardingView.swift

#97 
온보딩 뷰 스타 셀 크기를 수정했습니다.
너비에 대해선 스크린 사이즈에 따라 임의의 값을 설정했습니다
어떤 변경 사항이 있나요?

[Fix] 온보딩 뷰 스타 셀 높이 수정

---

star/star/Source/Core/Theme/Fonts.swift
star/star/Source/Glass/StarModalView.swift
star/star/Source/Glass/StarModalViewController.swift
star/star/Source/Glass/StarModalViewModel.swift
star/star/Source/Mun/StarList/StarListView/StarListCollectionViewCell.swift
star/star/Source/Mun/StarList/StarListView/StarListViewController.swift

#96 
스타 생성/수정 모달에 대한 입력값 에러에 대한 토스트 메세지 기능을 구현했습니다.
어떤 변경 사항이 있나요?
- `StarViewModel` `transform` 메서드는 글라쓰가 수정 예정
- 에러를 확인하고 코어데이터 저장 로직 수정 필요 

입력값 에러에 대한 토스트 메세지 기능 구현

---

star/star/Source/Eden/PermissionView.swift
star/star/Source/Eden/PermissionViewController.swift

#92 
PermissionView 권한 설정 안내 문구 수정완료 했습니다.
어떤 변경 사항이 있나요?
권한 설정 알럿 하이라이트는 도전을 잠시 멈추겠습니다.
또한 스크린 탑 to 알럿, 알럿 to 바텀으로 나눠서 label의 레이아웃을 조정하기로 했는데 이 부분도 새로 계획을 세워야할 것 같습니다. 사실 SE 버전 아니면 지금도 나쁘지 않은 것 같습니다.

PermissionView 문구 수정 

---

star/star/Source/Jerry/Star/JSONCodable.swift
star/star/Source/Jerry/Star/MockData.swift
star/star/Source/Jerry/Star/Schedule/Schedule.swift
star/star/Source/Jerry/Star/Schedule/StarTime/StarTime.swift
star/star/Source/Jerry/Star/Schedule/WeekDay/WeekDay.swift
star/star/Source/Jerry/Star/Star.swift
star/star/Source/Jerry/Star/UserDefaultsManager/StarIDFormatter.swift
star/star/Source/Jerry/Star/UserDefaultsManager/StarIDManager.swift
star/star/Source/Jerry/Star/UserDefaultsManager/StarUserDefaultsManager.swift
star/star/Source/Jerry/Star/UserDefaultsManager/StarUserDefaultsManagerTester.swift

#94 
UserDefaults 를 통한 Star 데이터 CRUD 구현 
어떤 변경 사항이 있나요?
@name-mun @AhnJunGyung 
기존 코드에 영향이 가지 않게 
StarManager 를 통한 데이터 관리로 추가 개선할 예정입니다.

CoreDataManager를 UserDefaultsManager로 리팩토링 #94

---

star/star/Source/Jerry/Star/StarManager.swift

#103
StarManager 의 데이터 관리 객체 StarUserDefaultsManager 로 수정하였습니다.
어떤 변경 사항이 있나요?

StarManager 의 데이터 관리 객체 StarUserDefaultsManager 로 수정 #103

---

star/star/Source/Mun/StarList/StarListModel/TimeUntilMidnight.swift
star/star/Source/Mun/StarList/StarListViewModel/StarListViewModel.swift

#106 
다음 날이 되면 날짜를 다시 fetch 하는 기능을 구현했습니다. 
어떤 변경 사항이 있나요?
- `TimeUntilMidnight` 을 사용하여 다음 날까지 남은 시간을 계산하여 `TimeInterval` 타입을 반환합니다.

다음 날이 되면 날짜를 다시 fetch 하는 기능 구현

---

star/star/Source/Core/UIComponent/GradientButton.swift
star/star/Source/Jerry/WeekDayButton.swift

#108 
WeekDay 를 사용하는 버튼 구현
- 선택 여부에 따른 방출
- 선택 여부에 따른 색상 변경
- 요일 입력값에 따른 뷰 반영
어떤 변경 사항이 있나요?

WeekDayButton 구현 #108

---

star/star/Source/Glass/StarModalView.swift
star/star/Source/Glass/StarModalViewController.swift
star/star/Source/Glass/StarModalViewModel.swift
star/star/Source/Jerry/WeekDayButton.swift
star/star/Source/Mun/StarList/StarListView/StarListViewController.swift

#110 
- 스타 수정하기 구현
- datePicker 오류 수정
어떤 변경 사항이 있나요?

스타 수정하기 구현 #110

---

README.md

closes #40 
어떤 변경 사항이 있나요?
- Approve 없이 Merge할 예정

1차 MVP 기준 README 작성 #40

---

star/star/Source/Glass/RestSettingModalViewController.swift

#123 
- 휴식하기 버튼 클릭하면 값 가져오는 것까지 구현했습니다.
어떤 변경 사항이 있나요?
<UIPikcerView 레이아웃 수정 전>
<UIPikcerView 레이아웃 수정 후>

휴식 시간설정 모달 UI 구현

---

star/star/Source/Mun/StarList/StarListView/StarListView.swift

#131 
휴식 버튼 U를 수정했습니다. 
어떤 변경 사항이 있나요?
- `Fonts` 리팩토링 필요 → 뷰 단위로 폰트가 정의되어 있어, 새로운 뷰가 추가될 때마다 새로 정의하는 것이 번거로움.

휴식 버튼 UI 수정

---

star/star/Source/Glass/RestSettingModalViewController.swift
star/star/Source/Glass/RestTimeUserDefaults+Extension.swift
star/star/Source/Glass/UserDefaultsManager.swift

#133
- 휴식 모달에서 휴식하기 버튼 누르면 종료시간을 저장하도록 구현했습니다.
어떤 변경 사항이 있나요?
- 종료시간 가져오는 메서드 : restEndTimeGet()
- 추가적으로 필요한 기능 있으면 말씀해주세요.
@name-mun , @daydreamplace 

휴식 UserDefaults 구현 #133

---

star/star/Source/Glass/RestSettingModalViewController.swift
star/star/Source/Glass/RestTimeUserDefaults+Extension.swift
star/star/Source/Glass/UserDefaults+RestTime.swift

#145
- UserDefaults 삭제하기 구현
어떤 변경 사항이 있나요?

휴식하기 UserDefaults 삭제 구현

---

star/star/Source/Glass/StarModalViewController.swift

#169
- 현재 동작방식 : textField에 입력을 했을때 placeholder가 사라짐
- 변경할 동작방식 : textField를 탭 했을때(입력 커서가 생겼을 때) placeholder가 사라짐
어떤 변경 사항이 있나요?
no comment

스타 모달 placeholder 동작방식 변경

---

star/star/Source/Glass/CustomPresentationController.swift

- 디바이스별 모달 높이 구분
어떤 변경 사항이 있나요?
iPhone SE
iPhone 16Pro

스타 모달 높이 디바이스별 대응

---

star/star.xcodeproj/project.pbxproj
star/star/Source/Glass/StarModalView.swift
star/star/Source/Glass/StarModalViewController.swift
star/star/Source/Glass/StarModalViewModel.swift

#168 
앱 선택이 되어있지 않거나, 시작 시간이 종료 시간보다 15분 이른지에 대한 검증 로직을 구현했습니다.
어떤 변경 사항이 있나요?

앱 선택 및 시간 토스트메세지 기능 추가

---

star/star/Source/Eden/Onboarding/OnboardingCollectionView.swift
star/star/Source/Eden/Onboarding/OnboardingModel.swift
star/star/Source/Eden/Onboarding/OnboardingViewModel.swift

#151 
에러 수정해 다시 올렸습니다.
어떤 변경 사항이 있나요?

온보딩 뷰 버그 삭제

---

star/star/Source/Core/Extension/DeviceActivityName+Extension.swift
star/star/Source/Core/Extension/FamilyAcitivitySelection+Extension.swift
star/star/Source/Core/Manager/BlockManager.swift
star/star/Source/Core/Manager/NotificationManager.swift
star/star/Source/Core/Manager/StarManager/StarManager.swift
star/star/Source/Model/Star/Schedule/StarTime/StarTimeFormatter.swift
star/star/Source/Model/Star/Schedule/WeekDay/WeekDayFormatter.swift
star/star/Source/Model/Star/Schedule/WeekDay/WeekDayTranslator.swift
star/star/Source/Presentation/Onboarding/OnboardingViewController.swift
star/star/Source/Presentation/Rest/RestStart/RestStartViewController.swift
star/star/Source/Presentation/Rest/Resting/RestingViewController.swift
star/star/Source/Presentation/StarDeleteAlert/StarDeleteAlertViewModel.swift
star/star/Source/Presentation/StarEdit/StarEditViewController.swift
star/star/Source/Presentation/StarList/StarListView/StarListCollectionViewCell.swift
star/star/Source/Presentation/StarList/StarListView/StarListView.swift
star/star/Source/Presentation/StarList/StarListView/StarListViewController.swift
star/star/Source/Presentation/StarList/StarListViewModel/StarListCollectionViewCellViewModel.swift

- [Chores] 불필요한 import 제거
어떤 변경 사항이 있나요?

[Chores] 불필요한 import 제거

---

star/DeviceActivityMonitor/DeviceActivityMonitor.entitlements
star/DeviceActivityMonitor/DeviceActivityMonitorRelease.entitlements
star/star/Resource/en.lproj/Localizable.strings
star/star/Resource/ko.lproj/Localizable.strings
star/star/Source/Core/Manager/FamilyControlsManager.swift
star/star/Source/Presentation/Onboarding/OnboardingViewModel.swift
star/star/Source/Presentation/StarList/StarListView/StarListView.swift
star/star/Source/Presentation/StarList/StarListView/StarListViewController.swift
star/star/Source/Presentation/StarRefresgAlert/StarRefresgAlertViewController.swift

#213 
휴식버튼을 숨기고, 새로고침 버튼을 추가했습니다.
어떤 변경 사항이 있나요?
크린샷 (선택)

휴식버튼 -> 새로고침 버튼 수정

---

star/star/Resource/en.lproj/Localizable.strings
star/star/Resource/ko.lproj/Localizable.strings
star/star/Source/Core/Extension/UserDefaults+Extension.swift
star/star/Source/Core/Manager/NotificationManager.swift
star/star/Source/Presentation/StarEdit/StarEditViewModel.swift
star/star/Source/Presentation/StarList/StarListViewModel/StarListViewModel.swift

#221 
- `release-1.0.2` 브랜치에서 발생한 버그를 수정하고, `develop` 브랜치에 반영합니다.
- 주로 기능 관련 버그 수정 및 최적화 작업이 포함되었습니다.
어떤 변경 사항이 있나요?
- 이 PR은 `1.0.2` 버전의 수정 사항을 `develop` 브랜치에 병합합니다.

Merge release-1.0.2 into develop (bug fixes)

---

star/star.xcodeproj/project.pbxproj
star/star/Resource/Localizable.xcstrings
star/star/Source/Core/Manager/BlockManager.swift
star/star/Source/Core/Manager/NotificationManager.swift
star/star/Source/Presentation/Rest/RestSettingModal/RestSettingModalViewController.swift
star/star/Source/Presentation/Rest/Resting/RestingViewModel.swift

#208 
휴식 기능을 디버깅했습니다.
휴식 푸쉬 알림 기능을 추가했습니다.
어떤 변경 사항이 있나요?

휴식 기능 디버깅 및 휴식 종료 푸쉬알림 

---

star/star/Resource/Localizable.xcstrings
star/star/Source/Presentation/StarEdit/StarEditViewController.swift
star/star/Source/Presentation/StarEdit/StarEditViewModel.swift

#248 
선택된 앱을 확인하기 위해 라벨에 표시하는 기능을 구현했습니다. 
어떤 변경 사항이 있나요?
| 전체 선택된 경우 | 일부 선택된 경우 |
|-------------|-------------|
| ![Screenshot 1](https://github.com/user-attachments/assets/61024a75-70b1-4dc1-85b1-55c2b8d63c6a) | ![Screenshot 2](https://github.com/user-attachments/assets/dc2d006f-04e1-4ce0-967c-a73469e2fe2f) |
- `blockListRelay`에서 값이 방출되면 검증을 통해 라벨에 표시

앱 선택 라벨 표시 구현

---

star/star/Source/Core/Theme/UIFont.swift
star/star/Source/Presentation/Delay/DelayView.swift
star/star/Source/Presentation/Rest/RestSettingModal/RestSettingModalViewController.swift
star/star/Source/Presentation/Rest/Resting/RestingViewController.swift
star/star/Source/Presentation/StarDeleteAlert/StarDeleteAlertViewController.swift
star/star/Source/Presentation/StarEdit/StarEditView.swift
star/star/Source/Presentation/StarEdit/StarEditViewModel.swift
star/star/Source/Presentation/StarEdit/TimePickerModal/TimePickerModalView.swift
star/star/Source/Presentation/StarList/StarListView/StarListView.swift

#254 
시작시간과 종료시간이 같은 경우, 스타가 생셩되지 않게 예외처리 했습니다.
버튼의 텍스트 굵기를 black -> bold 로 수정했습니다. 
어떤 변경 사항이 있나요?
시작시간과 종료시간이 같은 경우, 스타가 생셩되지 않게 예외처리 했습니다.
버튼의 텍스트 굵기를 black -> bold 로 수정했습니다. 

시작시간과 종료시간이 같은 경우, 스타 생성 방지 (into main)

---

README.md

한국어 README 업데이트
